### ISSUE TITLE
schematics

### ISSUE THREAD

**Issue by hazerty565** [harlab/CM4Ext_Nano_m2#2]
do you share schematic? I would like to views schematic in PDF?

Possible?

Thanks you

**Comment by harlab** [comment]
Hi @hazerty565 
Currently we're going to use pretty much the same approach as RPF: open software and reduced interface schematics where applicable.
If you're thinking of your own open source hardware, let us know - we might contribute
Also consider feature request for the boards in design stage

**Comment by hazerty565** [comment]
Ok no problem
